v1.1
Squashed commit of the following:

commit f968c0669a4fa3eb828652522d88418bd9a55376
Author: Ivan Nikitin <vantoozz@gmail.com>
Date:   Sun Feb 16 10:02:58 2020 -0500

    ~ version

commit 0f770aefc98d9767eb65306505ebb4e5db47e886
Author: Ivan Nikitin <vantoozz@gmail.com>
Date:   Sun Feb 16 09:50:21 2020 -0500

    ~ symfony console version

commit c265e33996cd0a5672f4bf1c150cc71adba09a42
Author: Ivan Nikitin <vantoozz@gmail.com>
Date:   Sun Feb 16 08:57:50 2020 -0500

    ~ travis build

commit b87c0630c5635237a3f70152ca43d477d64087a5
Author: Ivan Nikitin <vantoozz@gmail.com>
Date:   Sun Feb 16 08:55:47 2020 -0500

    ~ travis build

commit a51a1ba36a89d9d6da5b3eefb275d5f7c14ddd9b
Author: Ivan Nikitin <vantoozz@gmail.com>
Date:   Sun Feb 16 08:48:08 2020 -0500

    ~ travis build

commit 57d2b3e1e9fa3b92ccbffa13dbc3abca6cfd922e
Author: Ivan Nikitin <vantoozz@gmail.com>
Date:   Sun Feb 16 08:43:58 2020 -0500

    + suppress meter intent

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,65 +1,20 @@
 #!/usr/bin/env bash
 
-./vendor/bin/parallel-lint --no-colors --exclude vendor --exclude .idea .
-	if [ $? != 0 ]
-	then
-		echo "Fix errors before commit."
-		exit 1
-	fi
-
-./vendor/bin/phpstan analyze src --level=1
-	if [ $? != 0 ]
-	then
-		echo "Fix errors before commit."
-		exit 1
-	fi
-
-./vendor/bin/phpmnd src --non-zero-exit-on-violation
-	if [ $? != 0 ]
-	then
-		echo "Avoid magic numbers usage."
-		exit 1
-	fi
-
-./vendor/bin/phpcs --standard=psr2 src
-	if [ $? != 0 ]
-	then
-		echo "Fix code style before commit."
-		echo "Try run ./vendor/bin/phpcbf --standard=psr2 src"
-		exit 1
-	fi
-
-./vendor/bin/phpdoccheck -d src
-	if [ $? != 0 ]
-	then
-		echo "Add docblocks before commit."
-		exit 1
-	fi
-
-./vendor/bin/phpcpd src
-	if [ $? != 0 ]
-	then
-		echo "Copy-paste detected"
-		exit 1
-	fi
-
-./vendor/bin/phpmd src text phpmd.xml
-	if [ $? != 0 ]
-	then
-		echo "Fix errors before commit."
-		exit 1
-	fi
-
-./vendor/bin/phpunit --testsuite=unit
-	if [ $? != 0 ]
-	then
-		echo "Fix tests before commit."
-		exit 1
-	fi
-
-./bin/phpcdm src --non-zero-exit-on-violation
-	if [ $? != 0 ]
-	then
-		echo "Decrease source code density"
-		exit 1
-	fi
+docker run --rm  -v "$(pwd)":/opt/project "$(docker build -q -f=docker/php.dockerfile .)" /bin/bash -c \
+  "php /root/.composer/vendor/bin/phpcs --standard=psr2 src \
+&& php /root/.composer/vendor/bin/phpunit\
+&& php /root/.composer/vendor/bin/phpmd src text phpmd.xml\
+&& php /root/.composer/vendor/bin/phpcpd src\
+&& php /root/.composer/vendor/bin/phpmnd src --non-zero-exit-on-violation\
+&& php /root/.composer/vendor/bin/phpdoccheck -d src\
+&& php /root/.composer/vendor/bin/phpcs --standard=psr2 src\
+&& php /root/.composer/vendor/bin/phpstan analyze src --level=1\
+&& php /opt/project/bin/phpcdm src --non-zero-exit-on-violation
+"
+if [ $? != 0 ]; then
+  echo "Fix errors before commit."
+  echo "Try run \
+  docker run --rm -v \"\$(pwd)\":/opt/project \"\$(docker build -q -f=docker/php.dockerfile .)\" \
+  php /root/.composer/vendor/bin/phpcbf --standard=psr2 src"
+  exit 1
+fi
